---
title: "R Notebook"
output: html_notebook
---
 

## 5.1 The arules Package
```{r}
# load tidyverse package
library(tidyverse)

# load arules package
library(arules)

# load arulesViz package
library(arulesViz)

# install mlbench package
install.packages("mlbench")

# load mlbench package
library(mlbench)
```


## 5.2 Transactions
```{r}
# importing the Zoo dataset from mlbench library
data(Zoo, package = "mlbench")

# display the first 6 rows of Zoo dataset
head(Zoo)
```


```{r}
# create "trans" object to store transactions from Zoo dataset
trans <- transactions(Zoo)
```


```{r}
# View the summary of column 13
summary(Zoo[13])
```


```{r}
# creates a ggplot object
ggplot(Zoo, aes(legs))

# plots the data by adding the geom_bar 
+ geom_bar()
```


```{r}
# Display a frequency table to view the legs column in Zoo dataset
table(Zoo$legs)
```


```{r}
# this line filters  the Zoo animals out with 0 legs 
Zoo_has_legs <- Zoo %>% mutate(legs = legs > 0)

# generates a bar chart of Zoo animals having legs
ggplot(Zoo_has_legs, aes(legs)) + geom_bar()
```


```{r}
# Creates table to display number of Zoo animals with and without legs
table(Zoo_has_legs$legs)
```


```{r}
# This line selects Zoo dataframe and adds "leg" as the new column and make "leg" a factor column
Zoo_unique_leg_values <- Zoo %>% mutate(legs = factor(legs))

# Displays the firts 6 rows of legs column
head(Zoo_unique_leg_values$legs)
```


```{r}
# mutate Zoo dataframe to create a new variable "legs"
Zoo_discretized_legs <- Zoo %>% mutate(
  legs = discretize(legs, breaks = 2, method="interval")
)

# summarize the table of discretized legs 
table(Zoo_discretized_legs$legs)
```


```{r}
# Create a transactions object 
trans <- transactions(Zoo_has_legs)

# prints the transactions
trans
```


```{r}
# summarize the transactions object
summary(trans)
```


```{r}

# View the column names of the transactions object 
colnames(trans)
```


```{r}

# View the column names of the  Zoo dataframe
colnames(Zoo)
```


```{r}
# Create a matrix of the first three rows of the transactions object
as(trans, "matrix")[1:3,]
```


```{r}
# View the first three transactions from the transactions object 
inspect(trans[1:3])
```


```{r}
#Visualize the transactions object 
image(trans)
```


```{r}

# This line plots the top 20 items from the transactions object 
itemFrequencyPlot(trans,topN = 20)
```


```{r}
# This lines of code plots the support for each item in the transactions object
ggplot(
  tibble(
    Support = sort(itemFrequency(trans, type = "absolute"), decreasing = TRUE),
    Item = seq_len(ncol(trans))
  ), aes(x = Item, y = Support)) + geom_line()
```


```{r}
# The line of code below is meant to find the class of each column in the Zoo_has_legs dataframe 
sapply(Zoo_has_legs, class)
```


```{r}

# This line converts the logical columns to factors in the Zoo_has_legs dataframe
Zoo_factors <- Zoo_has_legs %>% mutate_if(is.logical, factor)

# The last line of code is meant to check the class of each column in the Zoo_has_legs dataframe 
sapply(Zoo_factors, class)
```


```{r}
# This line summarizes the dataframe "Zoo_factors"
summary(Zoo_factors)
```


```{r}
# Create a transactions object from the Zoo_factors dataframe 
trans_factors <- transactions(Zoo_factors)

# displays the trans_factors object
trans_factors
```


```{r}
# Plots the top 20 items from the trans_factors transactions object
itemFrequencyPlot(trans_factors, topN = 20)
```


```{r}
# Create a transactions object for only the insect type from the trans_factors transactions object and store it in the variable trans_insects
trans_insects <- trans_factors[trans %in% "type=insect"]

# displays the trans_insects transactions object
trans_insects
```


```{r}
# View the transactions in trans_insects transactions object
inspect(trans_insects)
```


```{r}

# Create a matrix of the first 10 rows and 5 columns from the vertical tidLists
vertical <- as(trans, "tidLists")

# View the matrix
as(vertical, "matrix")[1:10, 1:5]
```



## 5.3 Frequent Itemsets
```{r}
# Calculate the number of possible itemsets
2^ncol(trans)
```


```{r}
# Generates and store frequent itemsets from the transactions object in "its"
its <- apriori(trans, parameter=list(target = "frequent"))

 # Display the itemsets
its
```


```{r}
# Calculates the percent of the data represented by 5 rows
5/nrow(trans)
```


```{r}
# Creates frequent itemsets with a minimum support of 0.05 from the transactions object 
its <- apriori(trans, parameter=list(target = "frequent", support = 0.05))
 # displays the its transactions object
its
```


```{r}
# Sort the frequent itemsets by support 
its <- sort(its, by = "support")

# View the top 10 itemsets
inspect(head(its, n = 10))
```


```{r}
# Provides a visual representation of the size of the frequent itemsets
ggplot(tibble(`Itemset Size` = factor(size(its))), aes(`Itemset Size`)) + geom_bar()
```


```{r}
# View the frequent itemsets with size greater than 8
inspect(its[size(its) > 8])
```


```{r}
# View the first 10 maximal frequent itemsets
its_max <- its[is.maximal(its)]

# View the first 10 rules sorted by confidence
its_max
```


```{r}
# It views the first 10 maximal frequent itemsets sorted by support
inspect(head(its_max, by = "support"))
```


```{r}
# Find the closed frequent itemsets 
its_closed <- its[is.closed(its)]

# display closed frequent itemsets 
its_closed
```


```{r}
# View the first 10 closed frequent itemsets sorted by support 
inspect(head(its_closed, by = "support"))
```


```{r}
# create a new tibble containing counts of each itemsets 
counts <- c(
  frequent=length(its),
  closed=length(its_closed),
  maximal=length(its_max)
)

# create a bar chart using ggplot
ggplot(as_tibble(counts, rownames = "Itemsets"),
       # plot itemsets vs counts in bar chart
  aes(Itemsets, counts)) + geom_bar(stat = "identity")
```


## Association Rules
```{r}
# Find or Discover and calculate  the association rules
rules <- apriori(trans, parameter = list(support = 0.05, confidence = 0.9))
```


```{r}
#Print the number of rules
length(rules)
```


```{r}
# Inspect the first 6 rules
inspect(head(rules))
```


```{r}
#Check the quality of the rules
quality(head(rules))
```


```{r}
# Sort the rules in descending order of lift 
rules <- sort(rules, by = "lift")

# Inspect the first 10 rules
inspect(head(rules, n = 10))
```


```{r}

# Generate rules without any parameters
r <- apriori(trans_factors)

# Print the generated rules
r
```


```{r}
# print the size of the object in Mb
print(object.size(r), unit = "Mb")
```


```{r}
#Inspect the first 10 rules
inspect(r[1:10])
```


```{r}
#inspect() function displays the structure of an R object
inspect(head(r, n = 10, by = "lift"))
```


```{r}
 #calling function with given parameters
interestMeasure(rules[1:10], measure = c("phi", "gini"),trans = trans)
```


```{r}
# Add two new columns to quality(rules)
quality(rules) <- cbind(quality(rules),
   # Calculate the interest measures of rules based on "phi" and "gini"        
   interestMeasure(rules, measure = c("phi", "gini"),
        # Use the transaction data for calculation           
    trans = trans))
```


```{r}
# Inspect the head of the rules data by phi
inspect(head(rules, by = "phi"))
```


```{r}
# Get all elements of the itemLabels that contain "type="
type <- grep("type=", itemLabels(trans), value = TRUE)

# Print the result
type
```


```{r}
#Finds association rules using Apriori algorithm
rules_type <- apriori(trans, 
         #Defining the right-hand side of the rules
  appearance= list(rhs = type))
```


```{r}
#inspect the first few rows of the sorted data
inspect(head(sort(rules_type, by = "lift")))
```


## 5.5 Association Rule Visualization
```{r}
# Load arulesViz library
library(arulesViz)
```

```{r}
# Visualize the rules using graph
plot(rules)
```


```{r}
# Plot the rules data with the jitter control
plot(rules, control = list(jitter = 0))
```


```{r}
#Plotting the rules data
plot(rules, #specify the data to be plotted
     shading = "order" #specify the shading to be used
    ) #close the plot
```


```{r}
plot(rules,  # rules is a vector of values to be plotted
     method = "grouped" # used to plot grouped barplot
     )
```


```{r}
# Plot the association rules using a graph
plot(rules, method = "graph")
```


```{r}
# Plot the sorted rules
plot(head(rules, by = "phi", n = 100), method = "graph")
```


## 5.6 Interactive Visualizations
```{r}
# Load iris dataframe
data(iris)

#summarize the ris dataframe
summary(iris)
```


```{r}
#Transactions function is used to convert a data frame into a transaction object
iris_trans <- transactions(iris)
```


```{r}
# Inspect the first 6 rows
inspect(head(iris_trans))
```


```{r}
# Apply the apriori algorithm to the dataset with min support and min confidence
rules <- apriori(iris_trans, parameter = list(support = 0.1, confidence = 0.8))

# Print the rules
rules
```


```{r}
# Inspect the rules vector
inspectDT(rules)
```


```{r}
#Visualize the rule set in HTML format 
plot(rules, engine = "html")
```


```{r}
#Plot rules data using matrix method and html engine
plot(rules, method = "matrix", engine = "html") 
```


```{r}

#Plot rules data using graph method and html engine
plot(rules, method = "graph", engine = "html")
```


































































